lab1-Холковский
makometr/ADS-8304 pull request #1
Opened 2019-09-15 21:40 UTC by gagask

5-й вариант

2019-09-16 21:34 UTC, makometr requested changes
### Код
Статические переменные - хитро. Исправить ошибки. Довольно странный code-style.
### Тесты
Добавить тест с некорректными данными + поподробнее вывод при тестировании (хотя бы печатать нумерацию, отступы между тестами и входные данные)
### Отчёт 
Отсутствует

2019-09-16 21:34 UTC, makometr commented on Holkovskii/lab1/Source/lab1.c
> +			if(flag)test(n/i);
Понимаю компактно. Но лучше так не делать

2019-09-16 21:34 UTC, makometr commented on Holkovskii/lab1/Source/lab1.c
> +		free(path);
Ошибка работы с памятью.

2019-09-16 23:06 UTC, gagask commented on Holkovskii/lab1/Source/lab1.c
> +			if(flag)test(n/i);
Исправил

2019-09-16 23:08 UTC, gagask commented on Holkovskii/lab1/Source/lab1.c
> +		free(path);
Если дело в том, что выделялось недостаточно памяти, то исправил.

2019-09-17 08:20 UTC, makometr reviewed
### Тесты
В invalid должны лежать данные, которые программа вообще не будет обрабатывать, например, буквы.

### Отчёт

- Изменить фамилию преподавателя, табличка не нужна
- Изменить Цель работы - на Obj-C я не видел кода 😅
- Добавить раздел описание функций (да, по сути будет одна функция)

2019-09-17 16:04 UTC, makometr approved these changes

2019-09-19 10:51 UTC, merged