lab4 - Altukhov
makometr/ADS-8304 pull request #104
Opened 2019-11-10 23:34 UTC by Legendorik

Вариант 2-в

2019-11-17 15:40 UTC, makometr requested changes
Цель в отчёте не соотвествует действительности.
А как ввести данные с консоли? Как указать номер уровня для подсчёта узлов?

2019-11-17 15:40 UTC, makometr commented on Altukhov/lab4/Source/binaryTree.h
> +        infoArr[maxArrSize] = 0;
Странное решение, можно было бы и двумя пермеными обойтись

2019-11-18 16:39 UTC, Legendorik commented on Altukhov/lab4/Source/binaryTree.h
> +        infoArr[maxArrSize] = 0;
решил сгруппировать

2019-11-18 16:42 UTC, Legendorik commented
Ввод с консоли, если следовать указаниям, отправленным в начале семестра, не то чтобы обязателен, так что ввод только через файл. Добавил подсказки, сообщающие имя стандартного файла ввода.
Теперь можно ввести уровень, тесты также проверяют разные уровни
Некорректная цель подкралась из предыдущего отчета :(

2019-11-18 23:17 UTC, makometr approved these changes

2019-11-19 18:35 UTC, merged