lab1 - Zavrazhin
makometr/ADS-8304 pull request #13
Opened 2019-09-17 22:45 UTC by DmitriiZavrazhin

Вариант 26

2019-09-19 22:34 UTC, makometr commented
![image](https://user-images.githubusercontent.com/21985069/65285977-bdcc7e80-db46-11e9-9576-8f80c969c325.png)
в чём проблема?

2019-09-19 22:37 UTC, makometr commented
оформление отчёта - 👎

2019-09-22 07:57 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +#include <cstdlib>  // for memory reallocation
Нерелевантные комментарии

2019-09-22 07:58 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +Sequence<long long signed> Phi(Sequence<long long unsigned> &seq)
Не надо писать signed

2019-09-22 07:58 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +	void print()
нужно перегрузить оператор <<

2019-09-22 08:01 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +			T *tmp_array = (T *) realloc(this->array, this->capacity * sizeof(T));
Нельзя использовать realloc, используй new и копирование

2019-09-22 08:01 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +			T *tmp_array = (T *) realloc(this->array, this->capacity * sizeof(T));
Форматирование аля "T *tmp_array" оставляет желать лучшего

2019-09-22 08:03 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +	T *array = new T[initial_sequence_capacity];
Используй std::vector вместо массива + так будет легче реализовать операции добавления и т.п.

2019-09-22 08:04 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +	void operator=(const Sequence<T> &seq)
оператор= не должен возвращать void

2019-09-22 08:05 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +		++this->size;
Лучше писать += 1

2019-09-22 08:08 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +	template<typename... Ts>
зачем нужен Parameter pack?

2019-09-22 08:08 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +	template<typename... Ts>
+ 1

2019-09-22 08:10 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +	Sequence<T> left_third(size_t pos)
Есть ли проблема у такого подхода?

2019-09-22 08:13 UTC, RedHash commented on Zavrazhin/lab1/Source/main.cpp
> +				if(std::string("0123456789").find(*current) != std::string::npos)
Очень плохой способ проверки на цифру
Сравнивай коды символов

2019-09-23 09:46 UTC, reallyigor requested changes
Исправь : )

2019-09-23 16:35 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +#include <cstdlib>  // for memory reallocation
Убраны

2019-09-23 16:35 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +Sequence<long long signed> Phi(Sequence<long long unsigned> &seq)
Убрано

2019-09-23 16:35 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +	void print()
Метод print заменён на метод represent

2019-09-23 16:36 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +	T *array = new T[initial_sequence_capacity];
Теперь используется std::vector

2019-09-23 16:36 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +			T *tmp_array = (T *) realloc(this->array, this->capacity * sizeof(T));
Убрато, т.к. теперь используется std::vector

2019-09-23 16:36 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +	void operator=(const Sequence<T> &seq)
Исправлено

2019-09-23 16:37 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +		++this->size;
Исправлено

2019-09-23 16:37 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +	template<typename... Ts>
Добавлен комментарий по этому поводу

2019-09-23 16:37 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +	Sequence<T> left_third(size_t pos)
Неточность в цикле найдена и исправлена

2019-09-23 16:37 UTC, DmitriiZavrazhin commented on Zavrazhin/lab1/Source/main.cpp
> +				if(std::string("0123456789").find(*current) != std::string::npos)
Исправлено

2019-09-23 19:34 UTC, DmitriiZavrazhin commented
Оформление отчёта и ошибка при вводе тестовых данных исправлены

2019-09-23 20:53 UTC, reallyigor approved these changes

2019-09-25 11:31 UTC, merged