lab1 Poryvai
makometr/ADS-8304 pull request #14
Opened 2019-09-18 01:29 UTC by Pavel377dq

19 вариант

2019-09-19 22:38 UTC, makometr requested changes
Жду изменений, проговоренных при очной встрече

2019-09-19 22:39 UTC, makometr commented
https://github.com/makometr/ADS-8304/pull/13#issuecomment-533334363

2019-09-25 22:47 UTC, makometr requested changes
- Вертикальные оступы это, конечно, хорошо, но 5 строк это перебор
- переименовать папку
- lr1.cpp~ - это что?
- при вводе пустой строки программа уходить в бесконечный цикл
- отсутствует скрипт тестирования

2019-10-15 18:26 UTC, Pavel377dq commented
Что не так с отчетом?

2019-10-15 20:27 UTC, makometr commented
Отнеситесь, пожалуйста, в следующий раз к заполнению отчёта более добросовестно.

2019-10-15 20:27 UTC, makometr approved these changes

2019-10-19 13:40 UTC, merged