lab2 - Щука
makometr/ADS-8304 pull request #18
Opened 2019-09-18 22:38 UTC by AleksandrShuka

Вариант 15

2019-09-19 21:26 UTC, makometr requested changes
Во-первых, старый отчёт.
Во-вторых, возникли сомнения, что реализованная структура является иерархическим списком.

2019-09-23 20:08 UTC, makometr approved these changes

2019-09-23 20:08 UTC, makometr commented on Shuka/lab2/Tests/test_incorrect.txt
> +b
почему а и б неидентичны?

2019-09-23 20:08 UTC, makometr commented on Shuka/lab2/Source/mylist.h
> +    MyListP tail;
Объединение можно было бы использовать

2019-09-23 20:35 UTC, AleksandrShuka commented on Shuka/lab2/Tests/test_incorrect.txt
> +b
Потому что список по условию задается в скобках, т.е должен быть хотя бы один уровень вложенности, aaa и bbb не будут же являться списками, если я правильно понимаю. Если нет - могу исправить.

2019-09-25 11:49 UTC, merged