lab2 - Бутко
makometr/ADS-8304 pull request #19
Opened 2019-09-22 11:26 UTC by artbutko

Вариант 4. Отчёт скину позже.

2019-09-22 15:03 UTC, artbutko commented
Добавлен отчёт.

2019-09-22 17:28 UTC, makometr reviewed
### Код
Подключены библиотеки с++, поэтому считаю, что весь код написан на с++. Отсюда и замечания. 
Прошу исправить недочёты. В основном они связаны с С-style кодом, поэтому советую почитать что-нибудь про философию современного С++ и заменяемые им практики из С.

### В тестовые данные следует включить невалидные данные (программа не падает)

### В отчёт следует включить:
- описание использованной структуры данных (и код)
- прототипы описываемых функций

2019-09-22 17:28 UTC, makometr commented on Butko/lab2/Source/lab2.cpp
> +    int N, R, L, H, M;
Интересное решение по формату входных данных. Но без ~~ста грамм~~ отчёты не разобраться.
Лучше обозвать поля в структуре более осмысленно.

2019-09-22 17:28 UTC, makometr commented on Butko/lab2/Source/lab2.cpp
> +int fromFile(std::string path) {
Эта функция - явное нарушение ODR. Следует разделить на более обособленные логические части.

2019-09-22 17:28 UTC, makometr commented on Butko/lab2/Source/lab2.cpp
> +void *back(Node *&bin) {
void*?
эта ересь не должна появляться в коде на современном С++. Понимаю, что такое используется повсеместно в С, то оставьте это в прошлом.

2019-09-22 17:28 UTC, makometr commented on Butko/lab2/Source/lab2.cpp
> +void init(int n, int l, int r, Node *&bin) {
Никаких init! Используйте конструктор для таких целей. На защите буду рад знаниям о POD-типах в С++.

2019-09-22 17:28 UTC, makometr commented on Butko/lab2/Source/lab2.cpp
> +        while (iss >> numb) array.push_back(std::stoi(numb));
Исправьте форматирование. Цикл + выражение на одной строке не допускаются. 
Опустить {} при единственном выражении - простительно.

2019-09-22 17:28 UTC, makometr commented on Butko/lab2/Source/lab2.cpp
> +    Node *bin = new Node;
Советую на досуге обратить внимание на такую тему как "умный указатель" и "деструктор". Сейчас исправлений не требуется

2019-09-22 17:30 UTC, makometr requested changes
После изменений проверю на утечки

2019-09-23 17:05 UTC, artbutko commented
Есть ли смысл менять отчёт, если код и тесты не прошли accept? Я думаю нет, поэтому пока отчет без изменений.

2019-09-23 17:08 UTC, artbutko commented on Butko/lab2/Source/lab2.cpp
> +        while (iss >> numb) array.push_back(std::stoi(numb));
Исправлено.

2019-09-23 17:10 UTC, artbutko commented on Butko/lab2/Source/lab2.cpp
> +    int N, R, L, H, M;
Исправлено в глобальных масштабах:)

2019-09-23 17:10 UTC, artbutko commented on Butko/lab2/Source/lab2.cpp
> +int fromFile(std::string path) {
Исправлено. Теперь ее нет.

2019-09-23 17:10 UTC, artbutko commented on Butko/lab2/Source/lab2.cpp
> +void *back(Node *&bin) {
Исправлено.

2019-09-23 17:11 UTC, artbutko commented on Butko/lab2/Source/lab2.cpp
> +void init(int n, int l, int r, Node *&bin) {
Исправлено, больше не повторится

2019-09-23 17:12 UTC, artbutko commented on Butko/lab2/Source/lab2.cpp
> +    Node *bin = new Node;
Прочитано, но слишком поздно.

2019-09-23 20:16 UTC, makometr approved these changes

2019-09-23 20:16 UTC, makometr commented
> Есть ли смысл менять отчёт, если код и тесты не прошли accept? Я думаю нет, поэтому пока отчет без изменений.

к барьеру

2019-09-23 22:08 UTC, artbutko commented
Добавлен отчет!💥

2019-09-24 00:39 UTC, makometr commented
> Добавлен отчет!💥

можно

2019-09-25 11:50 UTC, merged