lab1 - Чешуин
makometr/ADS-8304 pull request #21
Opened 2019-09-23 11:46 UTC by Wintari

2019-09-23 20:13 UTC, RedHash commented on Cheshuin/lab1/Source/main.cpp
> +        getline(cin, command);
Поч не cin >> ?

2019-09-23 20:14 UTC, RedHash commented on Cheshuin/lab1/Source/main.cpp
> +    int command;
Инициализируй переменные чем-нибудь по-умолчанию

2019-09-23 20:15 UTC, RedHash commented on Cheshuin/lab1/Source/main.cpp
> +int readCommand(void){
Не пиши void, оставь просто пустые скобки

2019-09-23 20:25 UTC, reallyigor requested changes
Исправь и поставь Accepted

2019-09-23 20:30 UTC, RedHash commented
Ну и отчёт нормально отформатируй, а то Максим Сергеевич не примет 8)

2019-09-24 05:09 UTC, Wintari commented on Cheshuin/lab1/Source/main.cpp
> +        getline(cin, command);
cin >> считывает до следующего пробела, а не до переноса строки, не считанные символы остаются в потоке и уходят в следующий getline() или cin >>. Можно было бы использовать cin.ignore(). Кроме того, при считывании команды мне хочется знать, что пользователь точно ввёл её номер без сопутствующего мусора.

2019-09-24 05:24 UTC, Wintari commented on Cheshuin/lab1/Source/main.cpp
> +int readCommand(void){
Сделано

2019-09-24 05:24 UTC, Wintari commented on Cheshuin/lab1/Source/main.cpp
> +    int command;
Сделано

2019-09-25 11:36 UTC, makometr commented on Cheshuin/lab1/Source/main.cpp
> +enum types{
плюсик за перечислениие
посмотри на досуге про enum class

2019-09-25 11:37 UTC, makometr approved these changes

2019-09-25 11:38 UTC, merged