lab2 - Холковский
makometr/ADS-8304 pull request #22
Opened 2019-09-23 12:39 UTC by gagask

18 вариант

2019-09-23 20:41 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +typedef struct Node Node;
зачем это? 🤔

2019-09-23 20:41 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +		fscanf(file,"(");
Замени fscan на cin

2019-09-23 20:42 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +		FILE* file = fopen(argv[1], "r");
Замени FILE на fstream

2019-09-23 20:42 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +		FILE* file = fopen(argv[1], "r");
поч argv[1] открывается 2 раза?

2019-09-23 20:43 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +	std::string oper="";                      //
Короткое непонятное имя

2019-09-23 20:43 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +	while(str[ind] == ' '){ind++;} //переход к первому аргументу или скобочке
Тело цикла на след. строку

2019-09-23 20:44 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +	if (str[ind] == ')')           //проверка унарности
Юзлэсс комментарий

2019-09-23 20:45 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +		oper+=str[ind++];                 //
Форматирование - пробелы надо

2019-09-23 20:47 UTC, RedHash commented
Вывод в отчёте - поч нецелесообразно?

2019-09-23 20:49 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +void func(Node*&, std::string const&, std::map<std::string,bool> const&);
непонятное имя функции

2019-09-23 21:02 UTC, RedHash commented on Holkovskii/lab2/Source/bery.cpp
> +		while (1)                //нахождение соот-ей ')'
Непонятные названия переменных (:49, :50), + looks like списывание 8)

2019-09-23 21:05 UTC, reallyigor requested changes
Компилируй с флагами -Wall -Werror 

Source/bery.cpp:36:2: error: control may reach end of non-void function
      [-Werror,-Wreturn-type]
        }
        ^
1 error generated.
make: *** [lab2] Error 1

2019-09-23 21:23 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +typedef struct Node Node;
Убрал

2019-09-23 22:46 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +		fscanf(file,"(");
Заменил

2019-09-23 22:46 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +		FILE* file = fopen(argv[1], "r");
исправил

2019-09-23 22:46 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +	std::string oper="";                      //
заменил

2019-09-23 22:46 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +	while(str[ind] == ' '){ind++;} //переход к первому аргументу или скобочке
перенес

2019-09-23 22:47 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +	if (str[ind] == ')')           //проверка унарности
убрал

2019-09-23 22:47 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +		oper+=str[ind++];                 //
добавил

2019-09-23 22:47 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +void func(Node*&, std::string const&, std::map<std::string,bool> const&);
заменил

2019-09-23 22:47 UTC, gagask commented on Holkovskii/lab2/Source/bery.cpp
> +		while (1)                //нахождение соот-ей ')'
переименовал

2019-09-25 23:22 UTC, makometr commented
Утечек нет

2019-09-26 08:59 UTC, gagask commented
> Утечек нет

Пофиксил

2019-09-26 13:12 UTC, makometr commented
> > Утечек нет
> 
> Пофиксил

Интересно, где вы нашли утечки

2019-09-26 13:37 UTC, gagask commented
> > > Утечек нет
> > 
> > 
> > Пофиксил
> 
> Интересно, где вы нашли утечки

ну раньше я использовал exit(1), те деструкторы не вызывались. Это я и исправил

2019-10-01 12:57 UTC, gagask commented
> Компилируй с флагами -Wall -Werror
> 
> Source/bery.cpp:36:2: error: control may reach end of non-void function
> [-Werror,-Wreturn-type]
> }
> ^
> 1 error generated.
> make: *** [lab2] Error 1

Теперь буду всегда с ними компилить

2019-10-02 15:56 UTC, merged