lab is done
makometr/ADS-8304 pull request #29
Opened 2019-09-24 02:42 UTC by scissorsnatcher

2019-09-24 02:48 UTC, scissorsnatcher commented
Вариант 7

2019-09-25 21:30 UTC, makometr requested changes
Добавьте в отчёт тривиальное описание главный функций (прототип - что делает), переформулируйте цель и вывод
Добавить скрипт тестирования, улучшить меню
Нумерация тестов + отступы между ними
Считывание с консоли не работает

2019-09-25 21:30 UTC, makometr commented on Ivchenko/lab1/Source/lab1.cpp
> +using namespace std;
![image](https://user-images.githubusercontent.com/21985069/65640809-ded41a00-dff3-11e9-9bd5-216047ff9745.png)

2019-09-25 21:30 UTC, makometr commented on Ivchenko/lab1/Source/lab1.cpp
> +void IsFloat(string str, bool* b, int *flag1, int* flag2);
Контейнеры тоже следует передавать по ссылке. Если хотите указать на низменяемость - добавляйте const

2019-10-01 15:25 UTC, makometr requested changes
Кто у кого списывал? script != makefile, а по факту да
добавьте ключи компиляции Wall и Werror и исправите ошибки
нету скрипта тестирования

2019-10-02 16:01 UTC, makometr approved these changes

2019-10-02 16:01 UTC, merged