Ryzhickov_Alexander_lb2
makometr/ADS-8304 pull request #30
Opened 2019-09-24 03:13 UTC by AlexRyzhickov

2019-09-25 22:34 UTC, makometr requested changes
- Переименовать папку
- Sourse != Source 
- Скрипт не работает
```
./script: line 1: lab2:: command not found
g++.exe: error: Source/lab2.cpp: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
```

- присутствуют предупреждения при компиляции
- на последнем тесте утекло 642 байта. Первый рекорд в этом семестре, поздравляю!

2019-09-25 22:34 UTC, makometr commented on lab2/Sourse/lab2.cpp
> +using namespace std;
![image](https://user-images.githubusercontent.com/21985069/65641254-fc55b380-dff4-11e9-893e-b4695edad3ac.png)

2019-09-25 22:34 UTC, makometr commented on lab2/Sourse/lab2.cpp
> +typedef struct Node {
Здесь следует использовать union или std::variant

2019-10-01 17:13 UTC, AlexRyzhickov commented on lab2/Sourse/lab2.cpp
> +using namespace std;
using namespace std убал

2019-10-01 17:13 UTC, AlexRyzhickov commented on lab2/Sourse/lab2.cpp
> +using namespace std;
*убрал

2019-10-01 17:14 UTC, AlexRyzhickov commented on lab2/Sourse/lab2.cpp
> +using namespace std;
Переписал программу с использованием умного указателя, утечек быть не должно

2019-10-01 17:42 UTC, AlexRyzhickov commented on lab2/Sourse/lab2.cpp
> +using namespace std;
script рабочий

2019-10-01 17:42 UTC, AlexRyzhickov commented on lab2/Sourse/lab2.cpp
> +using namespace std;
посмотрите пожалуйста отчёт

2019-10-01 23:21 UTC, makometr requested changes
Скрипт делает ничего. 
Переименовать папку, работаем с своей директории!
Утечка исправлена.

2019-10-02 15:59 UTC, makometr commented
Исправить замечания выше

2019-10-07 15:15 UTC, AlexRyzhickov commented
Создал папку со своим именем, папку lab2 переместил в неё

2019-10-07 15:17 UTC, AlexRyzhickov commented
![Снимок экрана от 2019-10-07 18-04-22](https://user-images.githubusercontent.com/42917261/66324753-b53dbb80-e92e-11e9-9500-0bbb0d3f7da4.png)
скрипт робит

2019-10-07 17:17 UTC, makometr commented
Ок. Но в следующей лаба чтение тестов прямо внутри программы по захардкожженому пути принята не будет

2019-10-07 17:18 UTC, makometr approved these changes

2019-10-07 17:18 UTC, merged