lab1 - variant 9 done
makometr/ADS-8304 pull request #31
Opened 2019-09-24 06:53 UTC by Codedbyte

2019-09-25 22:39 UTC, makometr commented on Sani_Zayyad/lab1/Source/main.cpp
> +using namespace std;
![image](https://user-images.githubusercontent.com/21985069/65644965-72aae380-dffe-11e9-9409-8b159d7243ca.png)

2019-09-30 19:06 UTC, reallyigor requested changes
Нужно удалить бинарные файлы (.DS_Store из)

2019-09-30 19:07 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +//declaration of Functions
Не нужно оставлять нерелевантные комментарии

2019-09-30 19:08 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +void calculate(std::string input);
Имена функций не отражают суть их работы

2019-09-30 19:08 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +void ProceedInput()
Здесь и далее: не нужные комментарии

2019-09-30 19:09 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +    std::string FilePath = "/Users/sanizayyad/Documents/input.txt";
Путь до файла с тестами должен подаваться аргументов командной строки - у меня нет папки /Users/sanizayyad : )

2019-09-30 19:10 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +void ReadFromFile(std::string filename)
Лишнее копирование - передавай по константной ссылке

2019-09-30 19:10 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +    file.open(filename);
Вместо open, нужно передать название файла в конструктор:
например:
std::ifstream file(filename);

2019-09-30 19:11 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +        int super_count = 0;
Плохое название для переменной - не понятно, что она делает

2019-09-30 19:11 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +    file.close();
В C++ можно не вызывать эту функцию - она автоматически вызовется:
Почитай, что такое конструкторы / деструкторы

2019-09-30 19:12 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +    for (i; i < str.size(); i++)
Объявляй i внутри цикла:
for (int i = 0; i < str.size(); i++)

2019-09-30 19:13 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +bool expression(std::string str, int pos)
Лишнее копирование - нужна константная ссылка
Короткие + непонятные имена

2019-09-30 19:18 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +        std::string exp_1, exp_2, sign;
Короткие + непонятные имена переменных

2019-09-30 19:19 UTC, RedHash commented on Sani_Zayyad/lab1/Source/main.cpp
> +    std::string notExp = before == true ? "NOT(TRUE)" : "NOT(FALSE)";
Непонятно, что делает эта строчка. Надо разбить на несколько операций

2019-09-30 19:19 UTC, RedHash commented on Sani_Zayyad/lab1/Test/input.txt
> +(TRUE AND NOT(FALSE OR NOT(TRUE AND FALSE)))
Попробуй тест:
)TRUE AND FALSE(

2019-09-30 19:20 UTC, RedHash commented on Sani_Zayyad/lab1/script
> +	g++ Source/main.cpp -o lab1
Компилируй с флагами -Wall -Werror
g++ Source/main.cpp -Wall -Werror -o lab1

2019-09-30 19:22 UTC, RedHash commented
Отчёт оформлен плохо, лишний жирный шрифт, нет описания алгоритма (твоего алгоритма, а не задания)

2019-09-30 19:26 UTC, RedHash commented
Отсутствует скрипт тестирования

2019-10-02 16:12 UTC, makometr approved these changes

2019-10-02 16:12 UTC, merged