Chechetkina lab1
makometr/ADS-8304 pull request #32
Opened 2019-09-24 07:03 UTC by Chekess

2019-09-30 16:49 UTC, makometr requested changes
В отчёте отсутствует тестирование и код
В работе тоже отсутствует тестирование и скрипт запуска/сборки

2019-09-30 16:49 UTC, makometr commented on main.cpp
> +void MyRecursion::write(std::string MyText) {
Здесь лучше избавить от копирования аргумента и передавать по константной ссылке

2019-09-30 16:49 UTC, makometr commented on main.cpp
> +    int k = 0;
Лучше дать более осмысленные имена переменным

2019-10-02 16:23 UTC, makometr requested changes
Добавить тесты и скрипт запуска этих тестов
Исправить форматирование кода в отчёте

2019-10-03 19:30 UTC, backsapc requested changes
Норм, если не касаться оформления. Возможно стоит присмотреться к части комментариев.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +int MyRecursion::Recursion(int leftBorder, int rightBorder) {
Названия методов должны начинаться со строчной буквы.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +void MyRecursion::test(int leftBorder,int rightBorder){
Название должно отображать намерения. По названию непонятно, что делает функция.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +    bool flag = true;
Переменной следует дать осмысленное название. Что означает флаг?

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +    int symbCount = 0;
Не стоит сокращать symbol до symb.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +    if ((!flag) || (str[leftBorder+3] != '=') || (str[leftBorder+4] != '(') || (str[rightBorder] != ')')){
Сложное условие, следует дать название и вынести из if.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +        return 0;
Return может быть вынесен за пределы if.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +    MyRecursion Text;
Было бы круто сделать чтение из аргументов командной строки.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +    test(leftBorder,rightBorder);
Пробел после ','.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +    if (leftBorder>=rightBorder)
Пробел вокруг '>='.

2019-10-03 19:30 UTC, backsapc commented on main.cpp
> +        std::cout<<"yes";
Возможно стоит вынести вывод результатов за пределы функции и добавить функции осмысленное возвращаемое значение?

2019-10-07 17:03 UTC, makometr commented on main.cpp
> +        return 0;
> Return может быть вынесен за пределы if.

Он не в пределах if :)
просто нужно убрать отступ перед return

2019-10-07 17:05 UTC, backsapc commented on main.cpp
> +        return 0;
> > Return может быть вынесен за пределы if.
> 
> Он не в пределах if :)
> просто нужно убрать отступ перед return

![image](https://user-images.githubusercontent.com/18036840/66332592-bfb38180-e93d-11e9-84b8-c0c75ec3dbd0.png)
Как нет?)

2019-10-07 20:50 UTC, makometr commented on main.cpp
> +        return 0;
> > > Return может быть вынесен за пределы if.
> > 
> > 
> > Он не в пределах if :)
> > просто нужно убрать отступ перед return
> 
> ![image](https://user-images.githubusercontent.com/18036840/66332592-bfb38180-e93d-11e9-84b8-c0c75ec3dbd0.png)
> Как нет?)

Да, я слепой, простите

2019-10-07 21:07 UTC, backsapc approved these changes
1) Смотри, ошибки расписал, завтра (сегодня) буду принимать, но ошибки жельно поправить) 
2) Не нашёл скрипта для тестирования 🙈 Без скрипта тестировать не умею, у меня лапки.
3) В отчете старые названия: (ну и как бы ладно)
![image](https://user-images.githubusercontent.com/18036840/66348572-88ee6300-e95f-11e9-94cb-bdb437670c7c.png).

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +        in.close();//��������� ����
Здарова) Лучше без комментов на самом деле.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +                Text.recursion(0, Text.length);
У тебя тут классик ошибка дизайна. Обычно, чтобы не приходилось делать вот так `Text.recursion(0, Text.length);` пишется функция хелпер с нулём аргументов, которая внутри уже вызывается `Text.recursion(0, Text.length);`. Выглядит так :
```
void notSoMainRecursion(){
    this.recursion(0, Text.length);
}
```
Сам совет тот же, не совать всё в одну кучу, сейчас функция делает слишком много)

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +                MyRecursion Text(line);
Local variables should start with lower case letter.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +    //std::cout << "Enter string" << "\n";
Не бойся удалять старый код.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +MyRecursion(std::string&);
Форматирование поплыло.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +    length = str.length()-1;
`str.length` возвращает size_t. Если окажется 0, то можешь получить прикол с переполнением 😉.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +    int length;
Не должно быть публичным, тем более открытым дня записи и чтения.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +    int recursion(int, int);
Переносится в приватный скоуп остаётся только публичный метод, который описан ниже.

2019-10-07 21:07 UTC, backsapc commented on Script.TXT
> +g++ ./main.cpp -o lab1
Расширение txt это очень мило 😉.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +    bool verification = true;
verification of what?

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +    symbolCount = 0;
Лучше назначить новую переменную, чем мутировать (изменять) старую.

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +    }
Это уже лучше, 👍

2019-10-07 21:07 UTC, backsapc commented on main.cpp
> +        Text.read(argv[1]);
Почему не считать в строку и не передать в конструктор?)

2019-10-07 21:08 UTC, backsapc commented on main.cpp
> +void MyRecursion::test(int leftBorder,int rightBorder){
Ну т.е. тут оно всё ещё непонятно, что делает функция))

2019-10-14 08:03 UTC, makometr commented
На моём компьютере нет папки D:/Study/Test
- плюсик за скрипт

2019-12-10 23:59 UTC, Pirozhochek commented
F

2019-12-29 20:08 UTC, closed without merging