lab3-Птухов
makometr/ADS-8304 pull request #34
Opened 2019-09-25 20:37 UTC by denisptuhov

2019-09-25 21:58 UTC, denisptuhov commented
Вариант 2(реализация на массиве)

2019-09-28 10:06 UTC, RedHash commented
Сегодня вечером проверю. Забавное название у 4 снизу коммита)

2019-09-28 19:41 UTC, reallyigor requested changes

2019-09-28 19:41 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.cpp
> +std::string getStringNumberValue(std::string& currentFileString)
функция говорит get string number value, а на деле ещё и изменяет строку (и неожиданное поведение). Нужно вынести в отдельную функцию изменение и переименовать эту

2019-09-28 19:41 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.cpp
> +		std::string currentFileString = "";
std контейнеры можно не инициализировать

2019-09-28 19:41 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.cpp
> +				try
как тут может возникнуть исключение, если ты проверяешь на то, что очередь не пустая перед pop? 🤔

2019-09-28 19:41 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.cpp
> +		std::cout << "Work complete let's eat!\n";
😃

2019-09-28 19:41 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.h
> +		size_t size() const
Молодец, что сделал константными ;)

2019-09-28 19:41 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.h
> +				data_ = resize(data_, capacity_, capacity_ + 10);
Магические константы

2019-09-28 19:41 UTC, RedHash commented on Ptuhov/lab3/Makefile
> +	g++ -c Source/Vecqu.cpp
Компилируй всё с флагами -Wall -Werror

2019-09-28 19:41 UTC, RedHash commented
В отчёте текст по левому краю сделай

2019-09-28 20:06 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.h
> +				data_ = resize(data_, capacity_, capacity_ + 10);
вроде бы никакой магии size_ - текущий размер массива(кол-во инициализированных элементов в нем), capacity_ - кол-во выделенной памяти, если вопрос адресован к +10, то добавляю сразу побольше чтобы не перевыделять память много раз

2019-09-28 20:07 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.cpp
> +				try
Добавлено просто для полноты интерфейса

2019-09-28 20:10 UTC, denisptuhov commented on Ptuhov/lab3/Makefile
> +	g++ -c Source/Vecqu.cpp
А как же с pragma once быть? -Wall поправлю

2019-09-28 20:26 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.h
> +				data_ = resize(data_, capacity_, capacity_ + 10);
Магическое число - когда в коде стоит рандомное число, и не понятно, почему оно там и почему такое. Вынеси в отдельную именованную константу

2019-09-28 20:32 UTC, denisptuhov commented on Ptuhov/lab3/Makefile
> +	g++ -c Source/Vecqu.cpp
готово

2019-09-28 20:33 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.cpp
> +				try
готово

2019-09-28 20:33 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.cpp
> +		std::string currentFileString = "";
готово

2019-09-28 20:33 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.cpp
> +std::string getStringNumberValue(std::string& currentFileString)
готово

2019-09-28 20:35 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.h
> +				data_ = resize(data_, capacity_, capacity_ + 10);
поправило

2019-09-28 20:37 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.cpp
> +std::string getStringNumberValue(std::string& currentFileString)
(надеюсь такой вариант изменений пойдет)

2019-09-28 20:38 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.h
> +				size_t newVectorCapacity = capacity_ + 10;
Я имел ввиду дать название числу 10)

2019-09-28 20:43 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.h
> +				size_t newVectorCapacity = capacity_ + 10;
готово

2019-09-28 20:54 UTC, RedHash commented on Ptuhov/lab3/Source/Vecqu.cpp
> +std::string getStringNumberValue(std::string& currentFileString, stringIteratorsPair& numberIt)
Константность забыл

2019-09-28 21:04 UTC, denisptuhov commented on Ptuhov/lab3/Source/Vecqu.cpp
> +std::string getStringNumberValue(std::string& currentFileString, stringIteratorsPair& numberIt)
готово

2019-10-02 16:02 UTC, makometr approved these changes

2019-10-02 16:02 UTC, merged