lab3 - Холковский
makometr/ADS-8304 pull request #35
Opened 2019-09-26 15:56 UTC by gagask

Вариант 2-д с реализацией очереди через список

2019-09-30 19:29 UTC, RedHash commented on Holkovskii/lab3/Source/queue.cpp
> +		Elem(char new_val):val(new_val),next(nullptr){}
форматирование, пробельчики там

2019-09-30 19:29 UTC, reallyigor requested changes
Форматирование кода плохое - пробельчики там, отступы нужны  (если на 2 балла за код)

2019-09-30 19:31 UTC, RedHash commented
Описание алгоритма == описание задания, пофикси

2019-09-30 19:32 UTC, RedHash commented on Holkovskii/lab3/Source/queue.cpp
> +	}
можно так:
return Head == nullptr;

2019-09-30 19:33 UTC, RedHash commented on Holkovskii/lab3/Source/queue.cpp
> +		queue* point = new queue;
зачем здесь new?

2019-09-30 21:14 UTC, gagask commented on Holkovskii/lab3/Source/queue.cpp
> +	}
сразу в голову не пришло))

2019-09-30 21:14 UTC, gagask commented on Holkovskii/lab3/Source/queue.cpp
> +		queue* point = new queue;
хороший вопрос

2019-10-01 11:07 UTC, RedHash commented
Форматирование не соответствует доку https://docs.google.com/document/d/1cNehOp2Qtnv_ER565V1KOMr-8RW9XmUM-PbE_wHKT8c/edit#heading=h.m9gi8uqr337j
Как минимум открывающая скобка то на текущей, то на следующей строке

2019-10-01 12:08 UTC, gagask commented
> Форматирование кода плохое - пробельчики там, отступы нужны (если на 2 балла за код)



> Форматирование не соответствует доку https://docs.google.com/document/d/1cNehOp2Qtnv_ER565V1KOMr-8RW9XmUM-PbE_wHKT8c/edit#heading=h.m9gi8uqr337j
> Как минимум открывающая скобка то на текущей, то на следующей + пробелов мало отсыпал :)

Отформатировал по требованиям из дока как смог)

2019-10-08 12:41 UTC, makometr approved these changes

2019-10-08 12:41 UTC, merged