lab2 - Mukhin
makometr/ADS-8304 pull request #38
Opened 2019-09-27 20:56 UTC by mukhamux

2019-09-30 16:07 UTC, makometr requested changes
При запуске тестовых данных программа падает. 
![image](https://user-images.githubusercontent.com/21985069/65896180-6daab300-e3b5-11e9-80b7-b995f3f3c636.png)

В тестовый скрипт добавить отступы, нумерацию и некрасивые данные

2019-09-30 16:07 UTC, makometr commented on Mukhin/lab2/Source/lab2.cpp
> +static std::ifstream in("/home/mukhamux/CLionProjects/algoritms/lab2/tests.txt");
Что за ужас! Мало того, что глобальная переменная, так ещё и абсолютный путь.

2019-09-30 16:07 UTC, makometr commented on Mukhin/lab2/Source/lab2.h
> +    s_expr* hd;
Советую давать более осмысленные названия полям.
(если этот код  можно использовать, что его можно не менять)

2019-09-30 16:07 UTC, makometr commented on Mukhin/lab2/Source/lab2.h
> +    int head = 0, tail = 0;
Не следует инициализировать несколько переменных на одной строке

2019-09-30 17:03 UTC, mukhamux commented on Mukhin/lab2/Source/lab2.cpp
> +static std::ifstream in("/home/mukhamux/CLionProjects/algoritms/lab2/tests.txt");
С учётом небольших изменений (не думаю, что из-за них валилось) у меня вывод следующий: 
![Screenshot from 2019-09-30 20-01-31](https://user-images.githubusercontent.com/42898147/65899898-62f41c00-e3bd-11e9-8750-0ae04157f734.png)

2019-10-01 15:17 UTC, makometr requested changes
1) Нету проверки на наличие аргумента командной строки - segfault
2) Неправильное использование заголовочных файлов - в них не должно быть реализации (в случае нешаблонных классов)
3) Ошибка с segfault не исправлена. (подсказка: 135 строка в hpp)

2019-10-01 19:54 UTC, mukhamux commented
> 1. Нету проверки на наличие аргумента командной строки - segfault
> 2. Неправильное использование заголовочных файлов - в них не должно быть реализации (в случае нешаблонных классов)
> 3. Ошибка с segfault не исправлена. (подсказка: 135 строка в hpp)

Всё исправил, кроме последнего. Не могу понять как может валиться на проверке поля типа bool, в которую заходят лишь тогда, когда у нас есть экземпляр класса, содержащий это поле, != nullptr. Ещё и на разных машинах по-разному отрабатывает...

2019-10-01 23:26 UTC, makometr commented
![image](https://user-images.githubusercontent.com/21985069/66007641-e6943280-e4bb-11e9-8ff8-99929561ea42.png)
p - print
bt - стек вызовов
Судя по всему, или в x мусор, или эта память уже была освобождена, что в принципе, одно и то же

2019-10-07 18:06 UTC, makometr commented
Снова не работает, но я нашёл ошибку

2019-10-07 18:20 UTC, mukhamux commented
Не подскажите в каком месте?

2019-10-07 18:21 UTC, mukhamux commented
@makometr не подскажите, в каком месте?

2019-10-07 20:36 UTC, makometr commented
> @makometr не подскажите, в каком месте? Тоже segmentation fault?

в том же самом месте, то и в стектрейсе сверху

2019-10-07 20:37 UTC, makometr commented
> @makometr не подскажите, в каком месте? Тоже segmentation fault?

Хорошо. Ошибка возникает из-за отсутствующего конструктора

2019-10-08 12:45 UTC, makometr approved these changes

2019-10-08 12:45 UTC, merged