lab1-Птухов
makometr/ADS-8304 pull request #4
Opened 2019-09-16 17:16 UTC by denisptuhov

2019-09-16 17:19 UTC, denisptuhov commented
Вариант 14

2019-09-16 22:03 UTC, makometr requested changes
### Код
Исправить замечание ниже, остальное работает. На возможные исправления укажу на очной встрече.
### Тесты

- Добавить возможность запуска всех сразу
- Добавить некорректные данные

### Отчёт
- Шаблон оформления отчётов с сайта для лабораторных по программированию не имеет смысла. 
Оформите, пожалуйста, в соответствии с зовом сердца и пунктами в требованиях (которые в репозитории).
Подсказка: кол-во пунктов в отчёте = кол-во пунктов в отчёте
- В отчёте указать вариант
- На будущее: тестирование предполагает один скрин с работой программы и далее табличку тестов с возможными пояснениями (как в отдельном файле в pdf)
- Вывод на троечку

2019-09-16 22:03 UTC, makometr commented on Ptuhov/lab1/Source/Programm.cpp
> +std::string bool_to_string(bool a)
Хоть различных велосипедов тут и много, но вот от этого точно надо избавляться - поищи как

2019-09-17 05:06 UTC, denisptuhov commented on Ptuhov/lab1/Source/Programm.cpp
> +std::string bool_to_string(bool a)
Что именно нужно исправить в рекурсивном вызове функции? Счетчик глубины? Или постоянную передачу потока вывода?

2019-09-17 05:09 UTC, denisptuhov commented on Ptuhov/lab1/Source/Programm.cpp
> +std::string bool_to_string(bool a)
По поводу тестов - предполагалось, что запуск всех тестов будет осуществляться при помощи файлового ввода (с использованием пути по умолчанию) и что для большего 
кол-ва тестов файловый ввод и был сделан

2019-09-17 07:20 UTC, denisptuhov commented on Ptuhov/lab1/Source/Programm.cpp
> +std::string bool_to_string(bool a)
bool_to_string исправил

2019-09-17 07:33 UTC, denisptuhov commented on Ptuhov/lab1/Source/Programm.cpp
> +std::string bool_to_string(bool a)
Отчет исправил

2019-09-17 08:23 UTC, makometr commented on Ptuhov/lab1/Source/Programm.cpp
> +std::string bool_to_string(bool a)
А статусы кто менять будет? 🥇

2019-09-17 08:30 UTC, makometr reviewed
### Отчёт
Вывод потерялся, "Основные теор положения" совсем невпопад, добавить раздел описание функций (которые важны для алгоритма, не всех)

2019-09-17 16:03 UTC, makometr approved these changes

2019-09-19 10:52 UTC, merged