lab3 - Бутко
makometr/ADS-8304 pull request #44
Opened 2019-10-01 14:53 UTC by artbutko

2019-10-01 20:34 UTC, RedHash commented on Butko/lab3/Source/Stack.h
> +        if (isEmpty()) return  -1;
char -1? 🤔

2019-10-01 20:37 UTC, RedHash commented on Butko/lab3/Source/Stack.h
> +    Stack():top(nullptr) {}
Ну раз уж ты изучил основы style guide, тогда пробелов отсыпь

2019-10-01 20:38 UTC, RedHash commented on Butko/lab3/Source/Stack.h
> +        node_* prev_;
поч имена полей кончаются на _?

2019-10-01 20:48 UTC, reallyigor requested changes
исправь

2019-10-01 21:19 UTC, artbutko commented on Butko/lab3/Source/Stack.h
> +        node_* prev_;
так ведь структура расположена в приватной области класса?

2019-10-01 22:03 UTC, artbutko commented on Butko/lab3/Source/Stack.h
> +    Stack():top(nullptr) {}
отсыпано!🕺🏼

2019-10-01 22:04 UTC, artbutko commented on Butko/lab3/Source/Stack.h
> +        node_* prev_;
ладно, я поменял, везде разные мнения насчет названий переменных в private🧐

2019-10-01 22:05 UTC, artbutko commented on Butko/lab3/Source/Stack.h
> +        if (isEmpty()) return  -1;
char -1 < char 0 , пофиксил👷🏼‍♂️

2019-10-04 20:34 UTC, reallyigor approved these changes

2019-10-08 12:46 UTC, merged