lab1 - Nam
makometr/ADS-8304 pull request #48
Opened 2019-10-02 01:13 UTC by NamYoSeb

16 вариант

2019-10-03 20:08 UTC, backsapc requested changes
В целом норм. 
По отчёту встречаются повторения (см. стр. 3).
По коду замечания очень похожи, в основном код-стайл, но есть и очевидные ошибки.
Не хватает скрипта для тестирования, сам программа для тестирования непригодна, потому что ввод всегда приходится делать руками (да, даже в случае с файлом), надо делать такое через аргументы командной строки.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +// Функция для ведения диалога с пользователем по поводу формата вывода(Сделана для того, чтобы в случае ошибки пользователь мог ввести данные заново);
Круто переносить комментарий на следующую строку, так читать неудобно.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +std::string InDialog(int option);
То же.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +std::string outDialog(int option) {
Названия функций круто привести к единому стилю. Начинать со строчной буквы.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	std::cout << "\nChoise your output format(Press a number and after press Enter) :\n\n1)Console\n2)Your file(Write a path for your file or write name of file and it will be created in a directory wit
Как выше.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	if (option == 1)
Комментарий можно заменить наименованием для магической константы 1.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	else if (option == 2)
Также.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	std::cout << "Choise your input format(Press a number and after press Enter):\n\n1)Console\n2)Open your file(Write the path to your file)\n3)Exit\n4)For sensei ;)\nYour choise:";
То же самое.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	{
Как и в предыдущей функции.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +}
![image](https://user-images.githubusercontent.com/18036840/66158804-4d862880-e62f-11e9-8c87-aeec5354a7ac.png)
Функция с возвращаемым значением не void не возвращает значения, грубая ошибка.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +		Dialog();
Коряво, убиваешь стэк, можно переделать на возвращаемое значение и бесконечный цикл. (Хвостовую рекурсию).

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +}
То же пустое возвращаемое значение.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +			Result(inputData, workStream, 0);
Неговорящее название функции.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +					workStream << std::endl << "____________________________________________________________________________" << std::endl << "Your input: " + dataFile << std::endl << "Result: False - incorrect sym
____________________________________________________________________________ не читабельно.  ____________________________________________________________________________ Круто такое выносить в константы и вставлять переносы.
____________________________________________________________________________

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +void Result(std::string _data_, std::ostream& out, int i)
\_так\_ не надо :)

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +		return 1;
Возвращаем bool или int?)

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	return Analyzer(_data_, out, ++i);
На самом деле можно линеаризировать код, если вставить вызовы к Analyzer в конце каждого if. Читалось бы чуть проще.

2019-10-03 20:08 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	return Analyzer(_data_, out, ++i);
Но и так норм.

2019-10-07 19:17 UTC, NamYoSeb commented
Баловался с GitHub Desktop и набаловался, в коммитах мусор ;)

2019-10-07 19:43 UTC, backsapc reviewed
Ну в общем, на паре разберём по словам всё тобою написанное 😉

2019-10-07 19:43 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +}
![image](https://user-images.githubusercontent.com/18036840/66343105-969deb80-e953-11e9-9495-9e6a3d775c84.png)

Всё ещё 😒

2019-10-07 19:43 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +	int flag = 0;
А чего не bool? 😒

2019-10-07 19:43 UTC, backsapc commented on Nam/lab1/Source/lab1.cpp
> +		std::cout << "Impooooosible, errroooorrrrr";
Тогда зачем? 😒

2019-10-07 19:44 UTC, backsapc approved these changes

2019-10-07 19:46 UTC, backsapc commented
И ещё такая тема, у тебя скрипт только под баш, это круто, но не кроссплатформенно. В следующих надо иметь под обе популярные платформы.

2019-10-08 12:46 UTC, merged