Bocharov
makometr/ADS-8304 pull request #49
Opened 2019-10-02 07:48 UTC by UTHawk

2019-10-02 08:40 UTC, UTHawk commented
https://github.com/makometr/ADS-8304/pull/43

2019-10-08 12:55 UTC, makometr requested changes
снова кривое форматирование и там, и там

2019-10-08 12:55 UTC, makometr commented on Bocharov/lab1/Makefile
> +	g++ Source/lab1.cpp -o lab1
Допиши -Wall -Werror

2019-10-08 12:55 UTC, makometr commented on Bocharov/lab1/Source/lab1.cpp
> +	std::string substr1 = "";
Стандартные контейнеры не нужно инициализировать

2019-10-08 12:55 UTC, makometr commented on Bocharov/lab1/Source/lab1.cpp
> +	int k = 0;
![image](https://user-images.githubusercontent.com/21985069/66334544-f095b580-e941-11e9-8933-6d1e14fc73ca.png)

2019-10-08 12:55 UTC, makometr commented on Bocharov/lab1/Source/lab1.cpp
> +            std::cout << "Couldnt open file" <<std::endl;
какой file? следует указать

2019-10-08 12:55 UTC, makometr commented on Bocharov/lab1/Source/lab1.cpp
> +            std::cout << "* FROM THE FILE *" << std::endl;
А ещё лучше сделать так:
1)  Execute tests
2) Execute from file "data.in" / или просто from file и затем ввести название файла
3) Execute from stdin

Передайте остальным, кто будет делать таким способом, пожалуйста

2019-10-08 12:55 UTC, makometr commented on Bocharov/lab1/Source/lab1.cpp
> +            }
Специально такое форматирование убогое?

2019-10-08 12:55 UTC, makometr commented on Bocharov/lab1/Source/lab1.cpp
> +            std::cout << "* FROM THE FILE *" << std::endl;
Сейчас увидел start, можно и так, и так

2019-10-15 18:47 UTC, makometr approved these changes

2019-10-15 18:48 UTC, merged