lab2 - Sani_Zayyad
makometr/ADS-8304 pull request #60
Opened 2019-10-07 19:37 UTC by Codedbyte

2019-10-07 20:48 UTC, makometr reviewed
Отсутствует скрипт для запуска тестов, исправить форматирование в отчёте (отступы, шрифт и т.д.)

Будь готов ответить за unordored_list

2019-10-07 20:48 UTC, makometr commented on Sani_Zayyad/lab2/Source/hierachy.h
> +};
А где union? 
если нет union, зачем тогда flag?

2019-10-07 20:48 UTC, makometr commented on Sani_Zayyad/lab2/Source/hierachy.cpp
> +    nestedList.reset();
Это лишнее

2019-10-07 21:42 UTC, Codedbyte commented on Sani_Zayyad/lab2/Source/hierachy.h
> +};
Union не работает для классов, которые имеют конструктор и деструктор -(Smart pointer)
Можно использовать std::variant, но это немного сложно..
Флаг нужен для определения, является ли список атомом или нет (используется в алгоритмах, а также нужен для соответствия определению из методички)

2019-10-08 13:00 UTC, makometr requested changes
Исправить фамилию в отчёте
Добавить скрипт тестирования

2019-10-11 22:11 UTC, makometr approved these changes

2019-10-11 22:11 UTC, merged