lab4 - Mukhin
makometr/ADS-8304 pull request #65
Opened 2019-10-13 21:42 UTC by mukhamux

2019-10-14 22:05 UTC, makometr commented
![iterator copy](https://user-images.githubusercontent.com/21985069/66786092-e5b1c680-eee7-11e9-8b0d-fbf275acfa9b.jpg)

2019-10-14 22:11 UTC, makometr commented
Ну а если серьёзно, то если что-то в С++ зовёт себя итератором, то и вести себя оно должно как итератор. Т.е. быть совестимыми с STL-братьями и остальной приёмной семьёй. 
Прочитайте подробнее про iterator_traits на досуге.

2019-10-19 13:52 UTC, makometr requested changes
На 5 тесте утекло 832 байта. Непорядок.

2019-10-20 20:19 UTC, mukhamux commented
> На 5 тесте утекло 832 байта. Непорядок.

чёт непонятное происходит, решил отследить утечку через количество new и количество delete. Так вот, нашёл 4 места, где происходило новое выделение памяти, отчистил память по этим указателям, снова запустил через valgrind, итог: definitely lost: 1,072 bytes in 19 blocks вместо предыдущих 832)))

2019-10-23 19:23 UTC, makometr commented
> > На 5 тесте утекло 832 байта. Непорядок.
> 
> чёт непонятное происходит, решил отследить утечку через количество new и количество delete. Так вот, нашёл 4 места, где происходило новое выделение памяти, отчистил память по этим указателям, снова запустил через valgrind, итог: definitely lost: 1,072 bytes in 19 blocks вместо предыдущих 832)))

![image](https://user-images.githubusercontent.com/21985069/67426859-a0764e80-f5e3-11e9-994b-adadfac045bc.png)
12 мин 😎

2019-10-26 16:58 UTC, makometr reviewed
Осталось только фамилию в отчёте исправить

2019-10-26 23:02 UTC, mukhamux commented
> Осталось только фамилию в отчёте исправить

готово

2019-10-31 09:30 UTC, mukhamux commented
> Осталось только фамилию в отчёте исправить

я уже защитился 2 недели назад, замержте пожалуйста)

2019-11-01 12:50 UTC, makometr approved these changes

2019-11-01 12:50 UTC, merged