Baryshev - lab2
makometr/ADS-8304 pull request #68
Opened 2019-10-15 18:06 UTC by baryshevandriy

2019-10-15 18:11 UTC, baryshevandriy commented
Вариант 12

2019-10-15 19:40 UTC, makometr requested changes

2019-10-15 19:40 UTC, makometr commented on Baryshev/lab2/Source/HierarchicalListTest.cpp
> +};
Что за халява? куда юнион исчез?

2019-10-21 11:12 UTC, makometr requested changes
Что касается отчёта: необходимо добавить задание с номером варианта, переработать цель и вывод.

По программе: утечка памяти вследствие ошибки логики.
По тестам вопросов нет.

2019-10-21 11:12 UTC, makometr commented on Baryshev/lab2/Source/HierarchicalListTest.cpp
> +		y = NULL;
в 2к19 никто вместо NULL стоит использовать nullptr

2019-10-21 11:12 UTC, makometr commented on Baryshev/lab2/Source/HierarchicalListTest.cpp
> +	bool *compareHierarchicalResultPointer = &compareHierarchicalResult;
Зачем заводить новую переменную?

2019-11-01 12:37 UTC, makometr approved these changes

2019-11-01 12:37 UTC, merged