Masalykin lr 2
makometr/ADS-8304 pull request #69
Opened 2019-10-15 18:23 UTC by DanMsl

2019-10-15 19:54 UTC, makometr requested changes
Я просил больше не использовать Qt.

2019-10-15 19:54 UTC, makometr commented on Masalykin/lab2/Source/mylist.cpp
> +    */
Почему функция **построения** **_читает_** данные?

2019-10-15 19:54 UTC, makometr commented on Masalykin/lab2/Source/mylist.h
> +    char atom;
Куда юнион потерялся?

2019-10-15 19:54 UTC, makometr commented on Masalykin/lab2/Source/mylist.h
> +    Q_OBJECT
Почему внутри класс по _**работе**_ со списком лежат данные узла?

2019-10-15 19:58 UTC, makometr commented
Давайте так: я вам лично переношу дедлайн лабы на след неделю, и вы приносите на неё исправленную лабораторную без Qt. 
Согласны? (можете ещё предложить свой вариант)

2019-10-15 20:00 UTC, DanMsl commented
Я согласен.

вт, 15 окт. 2019 г., 22:58 Fialkovsky Maxim <notifications@github.com>:

> Давайте так: я вам лично переношу дедлайн лабы на след неделю, и вы
> приносите на неё исправленную лабораторную без Qt.
> Согласны? (можете ещё предложить свой вариант)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/makometr/ADS-8304/pull/69?email_source=notifications&email_token=AKHIAIY5X6BQ6CEKQ4ITFHLQOYOETA5CNFSM4JBAJJBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBKAYJA#issuecomment-542379044>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKHIAIZUAZNI6EK6ERNKAH3QOYOETANCNFSM4JBAJJBA>
> .
>

2019-10-21 21:16 UTC, makometr commented
g++ -c -Wall ./Source/main.cpp
./Source/main.cpp:3:23: fatal error: ioManager.h: No such file or directory
 #include "ioManager.h"
                       ^
compilation terminated.
Makefile:5: recipe for target 'main.o' failed
mingw32-make: *** [main.o] Error 1

Кто-то что-то, видимо, забыл

2019-10-21 21:56 UTC, makometr commented
![image](https://user-images.githubusercontent.com/21985069/67246121-413eff80-f466-11e9-875c-76f9fbf64e43.png)
Проблема осталась. Класс называется MyList, а данные содержит как узел. И при создании узла создается ощущение, что создается новый список.

![image](https://user-images.githubusercontent.com/21985069/67246337-d3df9e80-f466-11e9-90f7-bbfb75cdcae5.png)
Больше пробелы

2019-10-21 21:57 UTC, makometr approved these changes

2019-10-21 21:58 UTC, makometr reviewed
Поправить форматирование в отчёте

2019-10-23 09:05 UTC, merged