Samkaev/lab2
makometr/ADS-8304 pull request #70
Opened 2019-10-15 19:36 UTC by sidtheslooth20

variant 21

2019-10-15 20:24 UTC, makometr requested changes
В отчёт добавить описание алгоритма заполнения иерархического списка.
Исправить warning.
Исправить утечку памяти.
Нету запуска тестов
Это не script, это make

2019-10-15 20:24 UTC, makometr commented on Samakaev/Source/lab2.cpp
> +	}*/
Почему комменты остались?

2019-10-15 20:28 UTC, sidtheslooth20 commented on Samakaev/Source/lab2.cpp
> +	}*/
чтобы раскоментировав эти штуки, можно было оперативно вернуть отладочные выводы

2019-10-19 14:02 UTC, makometr commented
![image](https://user-images.githubusercontent.com/21985069/67146279-2a47b400-f292-11e9-9628-d10965580c88.png)
gcc version 9.1.0 (Ubuntu 9.1.0-2ubuntu2~16.04)

2019-10-19 14:08 UTC, makometr commented
Ну, чисто технически память не утекает. Но всё же есть серьёзная ошибка по работе с памятью.
Если найдёте сами, то минус будет минус полбалла, иначе - минус балл.

2019-10-19 19:41 UTC, sidtheslooth20 commented
А ещё умные указатели - круто

2019-10-21 11:14 UTC, makometr commented
Да, верно

2019-10-21 11:15 UTC, makometr approved these changes

2019-10-21 11:15 UTC, merged