Karabanov lab2
makometr/ADS-8304 pull request #72
Opened 2019-10-16 00:34 UTC by Roma37

2019-10-16 00:35 UTC, Roma37 commented
Вариант №7

2019-10-18 13:34 UTC, RedHash commented
Мало тестов

2019-10-18 13:34 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +/*рекурсивная функция создания списка*/
Здесь и далее: ненужные комментарии

2019-10-18 13:34 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +typedef struct list {
в C++ можно не писать typedef

2019-10-18 13:35 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +	char* str = (char*)calloc(200, sizeof(char));
Нельзя использовать сишную муть, нАда new

2019-10-18 13:35 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +	char c;
Непонятное название, не инициализирован

2019-10-18 13:36 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +	char* str = (char*)calloc(200, sizeof(char));
Здесь и далее)

2019-10-18 13:36 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +		char* estr; // указатель для отслеживания конца файла
непонятные названия переменных

2019-10-18 13:36 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +		strcat(path, argv[1]);
Надо использовать C++ строки (+ их можно удобно складывать)

2019-10-18 13:37 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +		fclose(fileTests);
Надо потоки ввода/вывода

2019-10-18 13:37 UTC, reallyigor commented on Karabanov/lab2/Source/ADS2.cpp
> +	list* Ierlist = createlist(str, &i, NULL);
непонятное название переменной

2019-10-18 13:38 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +// выходим из данного уровня рекурсии
Плохое форматирование

2019-10-18 13:38 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +// пока не конец списка
непонятные названия

2019-10-18 13:40 UTC, reallyigor requested changes
Нужны флаги -Wall -Werror при компиляции

2019-10-18 13:45 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +		estr = fgets(str, 199, fileTests); // считываем строку из файла
а если строка длиной в 201 символ? 🤔

2019-10-18 13:45 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +			return 0;
Если ошибка, нужно возвращать ненулевой код возврата

2019-10-18 13:48 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +list* CheckAndDelete(list* head, char x);
Если хочешь написать "and" в названии функции -> надо делать на 2 разные

2019-10-19 21:18 UTC, makometr commented on Karabanov/lab2/Source/ADS2.cpp
> +	char* str = (char*)calloc(200, sizeof(char));
> Здесь и далее)

Так, протестую, мб это написано на С? В чем тогда проблема?

2019-10-20 07:17 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +	char* str = (char*)calloc(200, sizeof(char));
А я думал есть требование писать на С++ 😈

2019-10-20 07:18 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +	char* str = (char*)calloc(200, sizeof(char));
+ парень подключает C++ header'ы, так что это явно не С)

2019-10-20 10:42 UTC, RedHash commented on Karabanov/lab2/makefile
> +	g++ ./Source/ADS2.cpp -o ADS_lab2
Добавить флаги компиляции: -Wall -Werror

2019-10-23 23:53 UTC, Roma37 commented
Отчёт, пока не переделал, подожду по этому коду замечаний

2019-10-28 11:12 UTC, RedHash commented
Сегодня вечером проверю

2019-10-28 21:02 UTC, Roma37 commented
![hatiko_50611562_orig_](https://user-images.githubusercontent.com/42891268/67717756-6213d180-f9df-11e9-94e4-a58416bcc024.jpeg)

2019-10-29 12:20 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +		(*head) = (*head)->next;
Лишние скобки слева от равно

2019-10-29 12:23 UTC, RedHash commented
Исправь названия функция - надо либо coolFunc, либо cool_func

2019-10-29 19:20 UTC, RedHash commented on Karabanov/lab2/Source/ADS2.cpp
> +using namespace std;
ой-ой

2019-10-29 20:40 UTC, Roma37 commented on Karabanov/lab2/Source/ADS2.cpp
> +using namespace std;
Какая-то магия, не помню, чтобы его писал, сейчас исправим

2019-10-30 10:51 UTC, Roma37 commented
Сам не буду править 
но было бы вот так, если бы не слетел интернет [++][+][+][]

2019-11-01 12:58 UTC, merged