lab4 - Воропаев
makometr/ADS-8304 pull request #74
Opened 2019-10-20 22:23 UTC by StiXs221

Вариант 5-В

2019-10-21 12:01 UTC, makometr requested changes
![image](https://user-images.githubusercontent.com/21985069/67203171-1e373000-f413-11e9-8a88-581567e7ade7.png)
![image](https://user-images.githubusercontent.com/21985069/67203368-9867b480-f413-11e9-89d4-3296aecaffd0.png)

2019-10-21 12:01 UTC, makometr commented on Voropaev/lab4/Sources/BinTree.h
> +    typedef struct Element{
А зачем typedef? =/

2019-10-21 12:01 UTC, makometr commented on Voropaev/lab4/Sources/BinTree.h
> +    elem** array;
Выставлять наружу доступ к данным и памяти - не самая лучшая идея

2019-10-21 14:43 UTC, StiXs221 commented on Voropaev/lab4/Sources/BinTree.h
> +    typedef struct Element{
Убрал

2019-10-21 14:43 UTC, StiXs221 commented on Voropaev/lab4/Sources/BinTree.h
> +    elem** array;
Убрал

2019-10-21 21:00 UTC, makometr requested changes
720 bytes leak.

2019-10-23 08:32 UTC, makometr approved these changes
На титульнике в отчёте не нужна рамка

2019-10-23 08:33 UTC, merged