[REPORT LATER]lab2-Кирьянов
makometr/ADS-8304 pull request #78
Opened 2019-10-21 19:27 UTC by dnlka

Вариант 2

2019-10-21 21:47 UTC, makometr requested changes
![image](https://user-images.githubusercontent.com/21985069/67245648-25872980-f465-11e9-990c-85045c7dc421.png)
Исправить предупреждения

2019-10-21 21:47 UTC, makometr commented on Kiryanov/lab2/Source/lab2.cpp
> +typedef struct binkor {
typedef в с++ в этом случае не нужен

2019-10-21 21:47 UTC, makometr commented on Kiryanov/lab2/Source/lab2.cpp
> +		kor = new binkor;
Почему бы не объединить эти строки?

2019-10-21 21:47 UTC, makometr commented on Kiryanov/lab2/Source/lab2.cpp
> +}
![image](https://user-images.githubusercontent.com/21985069/67245301-56b32a00-f464-11e9-9824-5ba4945dd694.png)
![image](https://user-images.githubusercontent.com/21985069/67245317-5adf4780-f464-11e9-8af2-3a2e48dea447.png)

Почему  так? Явное нарущение srp.

2019-10-21 21:47 UTC, makometr commented on Kiryanov/lab2/Source/lab2.cpp
> +			if ((array[i] != ' ' && !isdigit(array[i]))||Stack.empty()) {
тут только всевидящий сможет увидеть || между условиями

2019-10-21 22:04 UTC, dnlka commented on Kiryanov/lab2/Source/lab2.cpp
> +}
Сначала выполняется рекурсия, а затем сразу после получения нужных нам значений все подчищается.

2019-10-21 22:05 UTC, dnlka commented on Kiryanov/lab2/Source/lab2.cpp
> +		kor = new binkor;
Объединил

2019-10-21 22:05 UTC, dnlka commented on Kiryanov/lab2/Source/lab2.cpp
> +typedef struct binkor {
Исправил

2019-10-21 22:08 UTC, dnlka commented on Kiryanov/lab2/Source/lab2.cpp
> +			if ((array[i] != ' ' && !isdigit(array[i]))||Stack.empty()) {
Проверочка зрения пройдена, исправил.

2019-10-21 22:56 UTC, dnlka commented on Kiryanov/lab2/Source/lab2.cpp
> +}
На всякий случай вместо этого написал деструктор

2019-10-26 17:16 UTC, makometr approved these changes

2019-10-26 17:16 UTC, merged