lab2 Poryvai
makometr/ADS-8304 pull request #79
Opened 2019-10-21 20:08 UTC by Pavel377dq

2019-10-21 20:13 UTC, Pavel377dq commented
Добавлю ввод вывод из файла, отчет,скрипт, тесты
По коду что-то добавить исправить помимо того что написал сверху?

2019-10-21 21:24 UTC, makometr reviewed
Вместо NUll слудует использовать nullptr.

Память после тестов

2019-10-21 21:24 UTC, makometr commented on Poryvai/lab2/Source/lr_2.cpp
> +
Что за абракадабра с форматированием?

2019-10-21 21:24 UTC, makometr commented on Poryvai/lab2/Source/lr_2.cpp
> +using namespace std;
ZLO

2019-10-21 21:24 UTC, makometr commented on Poryvai/lab2/Source/lr_2.cpp
> +typedef s_expr* lisp;
Поля структуры необходимо инициализировать

2019-10-21 21:24 UTC, makometr commented on Poryvai/lab2/Source/lr_2.cpp
> +	else return (s->tag);
Это код для людей, а не для печатного отчёта на черновики.
Не надо экономить

2019-10-21 21:24 UTC, makometr commented on Poryvai/lab2/Source/lr_2.cpp
> +		if (p == NULL) { cerr << "Memory not enough\n"; exit(1); }
Не уверен, что такого рода ошибки стоит обрабатывать

2019-10-26 17:28 UTC, makometr commented
![image](https://user-images.githubusercontent.com/21985069/67623537-07d40e80-f82f-11e9-8f60-3fa8d08d51f1.png)

Всё-таки что-то да можно

2019-10-26 17:44 UTC, makometr requested changes
![image](https://user-images.githubusercontent.com/21985069/67623687-f68c0180-f830-11e9-9f54-6a976f5efe6a.png)
![image](https://user-images.githubusercontent.com/21985069/67623690-fd1a7900-f830-11e9-9585-c4ae15f8690e.png)
![image](https://user-images.githubusercontent.com/21985069/67623691-0572b400-f831-11e9-9f5d-6bfa5e0ea107.png)

Боюсь, но для сдачи л/б такой расклад невозможен. 
+ вообще не понятный вывод/интерфейс + мало тестов

Отчёт кривой

2019-10-27 18:10 UTC, Pavel377dq commented
Извиняюсь, мне еще просто сказали сделать проверку на бк, пока этим занимаюсь

2019-10-27 18:12 UTC, Pavel377dq commented
С памятью разберусь
По отчету что не так?)

2019-10-28 19:51 UTC, makometr commented
> С памятью разберусь
> По отчету что не так?)
Серьёзно?
Нету задания, скопированного из методички, цель сформулирована неверно, нету разбиений на разделы, названия функций следует хоть как-то выделать: _так_ или **так**, предъявленные тестовые данные никак не объяснены (да их к тому ещё и мало), кривой вывод, названия разделов не по центру, а слева.

2019-10-29 19:53 UTC, Pavel377dq commented
Чуть позже залью получше ввод

2019-10-29 21:48 UTC, makometr commented
Программа ушла в бесконечный цикл
![image](https://user-images.githubusercontent.com/21985069/67811826-ae7a1280-faae-11e9-92f6-e557b7307fb2.png)
И что нужно вводить дальше?
![image](https://user-images.githubusercontent.com/21985069/67811880-cf426800-faae-11e9-9124-a05d07df971d.png)
Отлично, удачно ввёл
![image](https://user-images.githubusercontent.com/21985069/67811943-f00abd80-faae-11e9-8685-e01ad6079fb9.png)

2019-11-01 12:46 UTC, makometr commented
Напоминаю, что в отчёте для следующей работы жду приличное оформление отчёта

2019-11-01 12:46 UTC, merged

2020-01-15 23:12 UTC, makometr commented
> _No description provided._

Можно также вариант указать хотя бы в PR.