lab2 - Ivchenko
makometr/ADS-8304 pull request #82
Opened 2019-10-22 01:15 UTC by scissorsnatcher

Вариант 9

2019-10-26 18:23 UTC, makometr requested changes
![image](https://user-images.githubusercontent.com/21985069/67624201-6cdf3280-f836-11e9-87e3-e4af480ffa2c.png)
![mem](https://user-images.githubusercontent.com/21985069/67624205-71a3e680-f836-11e9-8a07-04fcf1ecc884.jpg)

Под заданием подразумевается построение реального линейного списка.
Какое-то форматирование {} не очень понятное

2019-10-26 18:23 UTC, makometr commented
ах да, чуть не забыл: утечка.

2019-10-26 18:32 UTC, scissorsnatcher commented
А что по отчету и тестам?

2019-10-26 19:51 UTC, scissorsnatcher commented
![image](https://user-images.githubusercontent.com/42897068/67625164-feed3800-f842-11e9-9342-0eb2ec47f29e.png)

2019-10-28 18:54 UTC, makometr requested changes
Утечка + описание структуры данных в отчёт. Желательно улучшить окно ввода-вывода.

2019-10-28 18:59 UTC, scissorsnatcher commented
> Утечка + описание структуры данных в отчёт. Желательно улучшить окно ввода-вывода.

Вы про это? Если да, то что это может быть?
[image](https://user-images.githubusercontent.com/42897068/67708868-f83efc00-f9cd-11e9-8fae-e5fdf25cd20f.png)

2019-10-28 19:07 UTC, scissorsnatcher commented
@makometr И что значит FIXED в графе тестов? Вы имели ввиду accepted?

2019-10-28 19:55 UTC, makometr commented
> @makometr И что значит FIXED в графе тестов? Вы имели ввиду accepted?

да

2019-10-28 19:56 UTC, makometr commented
> > Утечка + описание структуры данных в отчёт. Желательно улучшить окно ввода-вывода.
> 
> Вы про это? Если да, то что это может быть?
> ![image](https://user-images.githubusercontent.com/42897068/67709046-4bb14a00-f9ce-11e9-964a-87f040015312.png)

Покажите, пожалуйста, версию valgrind и gcc

2019-10-28 20:06 UTC, scissorsnatcher commented
> > > Утечка + описание структуры данных в отчёт. Желательно улучшить окно ввода-вывода.
> > 
> > 
> > Вы про это? Если да, то что это может быть?
> > ![image](https://user-images.githubusercontent.com/42897068/67709046-4bb14a00-f9ce-11e9-964a-87f040015312.png)
> 
> Покажите, пожалуйста, версию valgrind и gcc

gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
Using Valgrind-3.13.0 and LibVEX

2019-10-28 20:28 UTC, makometr commented
> > > > Утечка + описание структуры данных в отчёт. Желательно улучшить окно ввода-вывода.
> > > 
> > > 
> > > Вы про это? Если да, то что это может быть?
> > > ![image](https://user-images.githubusercontent.com/42897068/67709046-4bb14a00-f9ce-11e9-964a-87f040015312.png)
> > 
> > 
> > Покажите, пожалуйста, версию valgrind и gcc
> 
> gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
> Using Valgrind-3.13.0 and LibVEX

gcc version 9.1.0 (Ubuntu 9.1.0-2ubuntu2~16.04)
valgrind-3.11.0
![image](https://user-images.githubusercontent.com/21985069/67715314-a94b9380-f9da-11e9-8878-7d91b90afadb.png)

2019-11-01 12:38 UTC, makometr approved these changes

2019-11-01 12:38 UTC, merged