lab3 - Cheshuin
makometr/ADS-8304 pull request #88
Opened 2019-10-26 22:40 UTC by Wintari

Вариант 5-д.
Код с реализацией шаблонного стека на динамической памяти и валидатора на основе LL-анализатора. Класс для работы с вводом-выводом взят из прошлой работы. Отчёт и тесты залью позже.
Статус:
[Код - есть]
[Тесты - нет]
[Отчёт - нет]

2019-10-29 18:52 UTC, RedHash commented on Cheshuin/lab3/Source/dynamicstack.h
> +#define DYNAMICSTACK_H
Быстрее писать #pragma once

2019-10-29 18:53 UTC, RedHash commented on Cheshuin/lab3/Source/dynamicstack.h
> +void DynamicStack<T>::push(T data)
Наверное нужно принимать по константной ссылке

2019-10-29 18:54 UTC, RedHash commented on Cheshuin/lab3/Source/dynamicstack.h
> +void DynamicStack<T>::push(DynamicStack stack)
И здесь

2019-10-29 18:54 UTC, RedHash commented on Cheshuin/lab3/Source/dynamicstack.h
> +void DynamicStack<T>::push(DynamicStack stack)
И далее

2019-10-29 18:55 UTC, RedHash commented on Cheshuin/lab3/Source/ioManager.cpp
> +    std::ifstream* inFileStream = static_cast<std::ifstream*>(curInStream_);
Как сложно : '(

2019-10-29 18:56 UTC, RedHash commented on Cheshuin/lab3/Source/node.h
> +T Node<T>::data(void)
Зачем это?

2019-10-29 18:56 UTC, RedHash commented on Cheshuin/lab3/Source/types.h
> +#endif // TYPES_H
?

2019-10-29 18:57 UTC, RedHash commented on Cheshuin/lab3/Source/validator.h
> +        FOBRACKET, //открывающая фигурная скобка
наверное, вместо комментариев стоило лучше назвать переменные

2019-10-29 18:58 UTC, RedHash commented on Cheshuin/lab3/makefile
> +
Нужны флаги -Wall -Werror

2019-10-29 18:58 UTC, reallyigor requested changes
Fix

2019-10-29 18:59 UTC, Wintari commented on Cheshuin/lab3/Source/types.h
> +#endif // TYPES_H
Остался лишний файл с прототипа, уберём.

2019-10-29 19:01 UTC, Wintari commented on Cheshuin/lab3/Source/validator.h
> +        FOBRACKET, //открывающая фигурная скобка
В данном случае хорошее название превращается в ROUNDOPENBRACKET, а в таком случае сами правила замены становятся практически нечитаемыми.

2019-10-29 19:02 UTC, Wintari commented on Cheshuin/lab3/Source/node.h
> +T Node<T>::data(void)
Инкапсуляция данных в узле, правильнее будет возвращать ссылку, исправим.

2019-10-29 19:05 UTC, Wintari commented on Cheshuin/lab3/Source/ioManager.cpp
> +    std::ifstream* inFileStream = static_cast<std::ifstream*>(curInStream_);
Класс универсальный для cin и fstream, поэтому для хранения используется их предок istream. Этот же класс использовался для обработки аргументов командной строки в прошлой лабораторной.

2019-10-29 19:05 UTC, Wintari commented on Cheshuin/lab3/Source/dynamicstack.h
> +void DynamicStack<T>::push(DynamicStack stack)
Пофиксим

2019-10-29 19:05 UTC, Wintari commented on Cheshuin/lab3/Source/dynamicstack.h
> +void DynamicStack<T>::push(T data)
Пофиксим

2019-10-29 19:06 UTC, Wintari commented on Cheshuin/lab3/Source/dynamicstack.h
> +#define DYNAMICSTACK_H
QtCreator пишет это сам, так что не быстрее)

2019-10-29 19:07 UTC, Wintari commented on Cheshuin/lab3/makefile
> +
Сделаем

2019-10-29 19:15 UTC, RedHash commented on Cheshuin/lab3/Source/node.h
> +T Node<T>::data(void)
А воид зачем?

2019-10-29 19:16 UTC, reallyigor commented on Cheshuin/lab3/Source/validator.h
> +        FOBRACKET, //открывающая фигурная скобка
правила замены? Факт в том, что ROBRACKET тоже нечитаемо, А ROUND_OPEN_BRACKET норм

2019-10-29 19:46 UTC, Wintari commented on Cheshuin/lab3/Source/node.h
> +T Node<T>::data(void)
Всё ещё иногда на автомате проскакивает, уберём

2019-10-29 19:50 UTC, Wintari commented on Cheshuin/lab3/Source/validator.h
> +        FOBRACKET, //открывающая фигурная скобка
Ниже rulesTable, т.к. использованы принципы работы LL-parser'а, в итоге 1 правило на 3 сущности занимало бы очень много места, как пример 3 правило превратилось бы {ROBRACKET, TEXT, RCBRACKET} превратится в 
{ROUND_OPEN_BRACKET, TEXT, ROUND_CLOSE_BRACKET}, что несколько длинновато. Собственно это единственная причина, почему использовались сокращение.

2019-10-29 19:50 UTC, Wintari commented on Cheshuin/lab3/Source/validator.h
> +        FOBRACKET, //открывающая фигурная скобка
Фиксить?

2019-10-29 20:12 UTC, RedHash commented on Cheshuin/lab3/Source/validator.h
> +        FOBRACKET, //открывающая фигурная скобка
Йеп. Можно, например, убрать слово bracket

2019-11-04 22:03 UTC, RedHash commented on Cheshuin/lab3/Source/dynamicstack.h
> +T DynamicStack<T>::onTop()
Может быть константным

2019-11-04 22:04 UTC, RedHash commented on Cheshuin/lab3/Source/dynamicstack.h
> +size_t DynamicStack<T>::size()
Может быть константным

2019-11-04 22:05 UTC, RedHash commented on Cheshuin/lab3/Source/node.h
> +typename Node<T>::NodeP Node<T>::next()
Раз тут возвращается копия - может быть константным

2019-11-04 22:05 UTC, RedHash commented on Cheshuin/lab3/Source/node.h
> +typename Node<T>::NodeP Node<T>::prev()
Раз тут возвращается копия - может быть константным

2019-11-04 22:07 UTC, RedHash commented
В отчёте поехало форматирование

2019-11-04 22:08 UTC, RedHash commented
Больше тестов с не правильными скобочными последовательностями

2019-11-05 05:22 UTC, Wintari commented on Cheshuin/lab3/Source/node.h
> +typename Node<T>::NodeP Node<T>::prev()
Тут возвращается умный указатель.

2019-11-05 05:22 UTC, Wintari commented on Cheshuin/lab3/Source/node.h
> +typename Node<T>::NodeP Node<T>::next()
Тут тоже.

2019-11-05 19:38 UTC, merged